server:
  port: 7000

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/alex-aa-84/panda_config-data.git
          searchPaths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
  security:
    user:
      name: root
      password: P@nd@WWF_M
