spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/alex-aa-84/panda_config-data.git
          searchPaths: panda_config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
  security:
    user:
      name: ${EUR_USER}
      password: ${EUR_PASS}
